version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-efs-demo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vczkj3abfc5w"
s3_prefix = "my-efs-demo-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SecurityGroupIds=\"sg-ba0404e6\" SubnetID=\"subnet-e39eb2cd\""
